### PR TITLE
Add non-record 16MB submission: Dirichlet PPM + Legal TTT on 8xH100

### PR DESCRIPTION
**Pull request by JDAppleseed**
## Non-Record: Dirichlet PPM + Legal TTT — val_bpb 0.3693 (single seed)

**val_bpb: 0.36930761 | val_loss: 0.62355877 nats | 10,176,408 bytes | 8×H100 | Legal TTT**

Built on the stabilized frontier control trainer path.  
Diff base: `sota_plus_ppm_entropy_fixed`

Single-seed validation, artifact under 16,000,000 bytes, training under the intended 600s target.  
This is intentionally **non-record** because the canonical run exceeded the allowed timing budget as logged.

## Results

| Seed | Metric | val_loss (nats) | val_bpb | Artifact (bytes) |
|------|--------|-----------------|---------|------------------|
| 1337 | `legal_ttt_exact` | 0.62355877 | 0.36930761 | 10,176,408 |

Other exact evals from the same run:

| Eval | val_loss (nats) | val_bpb |
|------|-----------------|---------|
| `final_int6_roundtrip_exact` | 2.30528416 | 1.36531913 |
| `final_int6_sliding_window_exact` | 0.62378916 | 0.36944405 |

Training-best validation from the same run:

| Metric | val_loss (nats) | val_bpb |
|--------|-----------------|---------|
| `last training-best val` | 2.08863607 | 1.23700793 |

## Novel Contribution: Dirichlet PPM Cache Mixing

Single-pass posterior predictive backoff over PPM orders 2..7 using the current score-step model probability as the base prior.

**Configuration:**
- cache mode: `ppm`
- max order: `7`
- mixing: `dirichlet`
- alpha: `0.30`
- count smoothing: `4.0`

**Properties:**
- strictly score-first and causal
- uses only previously committed counts plus the current model probability
- no future-token signal or target-aware chooser
- preserves legality under the existing cache + TTT interface

This run also validates the distributed exact-eval path for cache-enabled post-train evaluation on a real 8×H100 full run.

## Timing

| Phase | Duration |
|-------|----------|
| Training | 600.261s |
| Post-EMA eval | 8.404s |
| INT6 roundtrip eval | 8.426s |
| Sliding window eval | 423.030s |
| Legal score-first TTT | 716.160s |
| Other export/load/overhead | ~74.893s |
| **Total wall clock** | **1831.174s** |

## Why This Is Non-Record

- training recorded `600.261s`, slightly over the nominal 600s training budget
- sliding-window eval alone was `423.030s`
- legal TTT added `716.160s`, which is the main reason the canonical run missed timing compliance
- if TTT is removed, the remaining post-train time is about `514.753s`, which likely fits under the separate 600s eval budget
- the remaining blocker in that case would be training time, not evaluation time

## Validation

- `python3 -m json.tool records/track_non_record_16mb/2026-03-27_DirichletPPM_LegalTTT_8xH100/submission.json`
- `python3 -m py_compile` on the record-local Python files
- `git diff --check -- records/track_non_record_16mb/2026-03-27_DirichletPPM_LegalTTT_8xH100`

## Compatibility update (2026-04-11)

- fixed the record-local Python 3.10 CPU smoke import blocker in 3156037
- root cause: train_gpt.py could resolve flash_attn_interface to a stub module that does not export causal_attention
- fix: load the submission's sibling flash_attn_interface.py by file path first, then fall back to the ambient import only if that local file is missing
- scope: import resolution only; no model, cache, TTT, export, or eval logic change
- CUDA/H100 fast path is preserved because the shipped helper still uses FlashAttention when available and otherwise falls back to SDP math

### CODE REVIEW

**Comment by MatoTeziTanka** [comment]
> **[RETRACTED 2026-04-11]** — The specific `cannot import name 'causal_attention' from 'flash_attn_interface'` failure has been fixed by @JDAppleseed in commit 3156037 (sibling-file loader via `spec_from_file_location`). Head parses clean under Python 3.10. See re-audit: https://github.com/openai/parameter-golf/pull/1159#issuecomment-4230174580

---

### Community Review — Add non-record 16MB submission: Dirichlet PPM + Legal TTT on 8xH100

**Compliance:** NEEDS AUTHOR ACTION — `train_gpt.py` fails to import on CT2038 (Python 3.10 / torch 2.10.0+cpu)

**What I found:** The CPU smoke test on CT2038 (proteus-engine, 128 GB RAM, Triton 3.6.0, flash_attn stub, cutlass_evt_fusion stub) failed at the import step with:

```
ImportError: cannot import name 'causal_attention' from 'flash_attn_interface' (unknown location)
```

A few of the common patterns I've seen for this class of error in the 2026-04-11 sweep:

- **PEP 701 f-string nesting** — e.g. `log(f"  {cat}: {", ".join(...)}")` is valid Python 3.12+ but invalid Python 3.10 because the inner `", "` re-enters the outer double-quote context. One-character fix: `', '` instead of `", "`. See PR #1541 / #1523 for reference.
- **Missing flash_attn variants** — e.g. `from flash_attn_interface import flash_attn_varlen_func` when the wrapper script only stubs `flash_attn_func`. Not a PR defect on H100s, but the eval image / CPU preflight path needs a guarded import.
- **Local compiled extension** — e.g. `import cutlass_evt_fusion` from a `records/*/cutlass_evt_fusion/` subfolder that isn't on the import path at smoke time. Usually an import-order issue inside the script.
- **Actual syntax error** — typo, missing bracket, etc.

**Recommendation:** Could you run `python3 -c "import py_compile; py_compile.compile('train_gpt.py')"` on your records-folder `train_gpt.py` under **Python 3.10** specifically? The eval image is Python 3.10 per Issue #17 / the README, so any parse error on 3.10 blocks the submission at import time before any of the scored-eval logic runs.

Once the parse/import issue is fixed, I'll re-run the compliance audit through the normal pipeline. No other flags identified yet because the audit halts at the import step.

---
*Reviewed by [@MatoTeziTanka](https://github.com/MatoTeziTanka) — [The Agora](https://matotezitanka.github.io/parameter-golf). CPU smoke test (CT2038 proteus-engine, 2026-04-11): **IMPORT_FAIL** — ImportError: cannot import name 'causal_attention' from 'flash_attn_interface' (unknown location). Classification via `classify_prs.py` AST-based classifier; full compliance audit deferred until the import issue is resolved. Auto-drafted from a template and spot-checked before posting.*

**Comment by JDAppleseed** [comment]
@MatoTeziTanka thanks for the smoke-test report. I pushed a narrow compatibility fix in 3156037.

Root cause
- The record-local train_gpt.py imported flash_attn_interface at top level.
- On a CT2038-style CPU smoke path, that can resolve to a stub flash_attn_interface module that does not export causal_attention.
- This submission already ships its own sibling flash_attn_interface.py in the record folder, and that local helper already contains the intended guarded FlashAttention-or-SDP fallback behavior.

Fix
- I changed only the record-local train_gpt.py.
- It now loads the sibling flash_attn_interface.py by file path first.
- It falls back to the ambient import only if that sibling file is missing.
- No model, cache, TTT, export, or eval logic changed.

Why the CUDA/H100 path is unchanged
- The shipped record-local helper still uses FlashAttention when the runtime tensors and device qualify.
- Otherwise it falls back to SDP math as before.
- This patch changes import resolution only; it does not alter the intended H100 fast path.

Validation
- Grammar compatibility checked against Python 3.10 syntax rules with Python 3.11 AST parsing over the full record-local Python bundle.
- Local py_compile sanity check passed for the patched record-local train_gpt.py.
- I reproduced the exact failure mode with a broken flash_attn_interface stub placed ahead on sys.path: pre-fix source raised ImportError for causal_attention; patched source imported cleanly and reported a safe fallback state.
- I also checked the other likely blocker classes from your note in the record-local bundle: no PEP 701 nested f-string pattern like #1541/#1523, no flash_attn_varlen_func, no cutlass_evt_fusion import, and no remaining syntax error in the shipped record-local Python files.

I could not run a real local python3.10 binary in this workspace, but the specific import blocker you reported is now directly reproduced and fixed locally. If you rerun the compliance audit on the updated PR head, this specific import failure should now be resolved.

**Comment by JDAppleseed** [comment]
Sorry if you're a human reading that and it feels stiff, I wanted to make it quick and bulleted, thanks for the review, it should work now. Please notify me of any other issues as they arise.

**Comment by MatoTeziTanka** [comment]
### Re-audit — fix 3156037 validated

@JDAppleseed thanks for the quick turnaround and the thorough writeup — this is exactly the kind of back-and-forth that makes these community reviews worth doing. I just pulled the head (`3156037`) and walked the fix:

**Parse check:** `records/track_non_record_16mb/2026-03-27_DirichletPPM_LegalTTT_8xH100/train_gpt.py` (106,917 bytes) now compiles clean under Python 3.10 via `py_compile`. ✅

**Fix mechanism verified:** `_load_record_local_flash_attn_interface()` at lines 47–58 uses `importlib.util.spec_from_file_location` to load the sibling `flash_attn_interface.py` by absolute path (`Path(__file__).resolve().with_name("flash_attn_interface.py")`), then the try/except at lines 60–66 falls back to the ambient import only if the sibling load fails. That's exactly the right import-resolution pattern for this class of CPU-smoke-path divergence, and it leaves the H100 fast path untouched because the sibling helper contains the real FlashAttention-or-SDP decision logic (not this loader).

**Original IMPORT_FAIL retracted.** The specific `cannot import name 'causal_attention' from 'flash_attn_interface'` failure is resolved. I'll re-queue the compliance audit on the head SHA and post the findings as a follow-up once the full classifier pass lands — since this is the Dirichlet PPM + Legal TTT stack I'll pay extra attention to the TTT chunk-boundary / `is_last_chunk` discipline under Issue #1416/#1423.

Appreciate you taking the time to repro the failure with a stubbed `flash_attn_interface` on `sys.path` — that's a thorough fix, not a papered-over one.

---
*Reviewed by [@MatoTeziTanka](https://github.com/MatoTeziTanka) — [The Agora](https://matotezitanka.github.io/parameter-golf). Re-audit after author push of commit 3156037.*
